services:
  audiobookshelf-strm:
    container_name: audiobookshelf-strm
    build:
      context: .
      dockerfile: Dockerfile
    image: audiobookshelf-strm:latest
    ports:
      - "2048:80"
    environment:
      - TZ=Asia/Shanghai
      - STRM_SCAN_PROBE=0
      - STRM_SCAN_SKIP_PROBE_PATHS=/CloudNAS
      - STRM_DIRECT_URL_MAP=/CloudNAS=http://192.168.50.3:19798/dav
    volumes:
      - /vol1/1000/docker/audiobookshelf-strm/config:/config
      - /vol1/1000/docker/audiobookshelf-strm/metadata:/metadata
      - /vol1/1000/downloads/media/strm/有声书:/audiobooks:ro
      - /vol1/1000/CloudNAS:/CloudNAS:rshared
    restart: unless-stopped
